### ISSUE TITLE
Fails at npm run setup

### ISSUE THREAD

**Issue by abdallahkadour** [NativeScript/plugin-seed#31]
I have downloaded the project, it fails on `npm run setup with the following error`
info No lockfile found.
[1/4] 🔍  Resolving packages...
error Couldn't find package "rxjs" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
Error: Couldn't find package "ansi-colors" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/usr/local/lib/node_modules/yarn/lib/cli.js:750:123)
    at NpmResolver.<anonymous> (/usr/local/lib/node_modules/yarn/lib/cli.js:50683:15)
    at Generator.next (<anonymous>)
    at step (/usr/local/lib/node_modules/yarn/lib/cli.js:310:30)
    at /usr/local/lib/node_modules/yarn/lib/cli.js:321:13
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Couldn't find package "babel-loader" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/usr/local/lib/node_modules/yarn/lib/cli.js:750:123)
    at NpmResolver.<anonymous> (/usr/local/lib/node_modules/yarn/lib/cli.js:50683:15)
    at Generator.next (<anonymous>)
    at step (/usr/local/lib/node_modules/yarn/lib/cli.js:310:30)
    at /usr/local/lib/node_modules/yarn/lib/cli.js:321:13
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Couldn't find package "babel-plugin-istanbul" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/usr/local/lib/node_modules/yarn/lib/cli.js:750:123)
    at NpmResolver.<anonymous> (/usr/local/lib/node_modules/yarn/lib/cli.js:50683:15)
    at Generator.next (<anonymous>)
    at step (/usr/local/lib/node_modules/yarn/lib/cli.js:310:30)
    at /usr/local/lib/node_modules/yarn/lib/cli.js:321:13
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Couldn't find package "browserslist" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/usr/local/lib/node_modules/yarn/lib/cli.js:750:123)
    at NpmResolver.<anonymous> (/usr/local/lib/node_modules/yarn/lib/cli.js:50683:15)
    at Generator.next (<anonymous>)
    at step (/usr/local/lib/node_modules/yarn/lib/cli.js:310:30)
    at /usr/local/lib/node_modules/yarn/lib/cli.js:321:13
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Couldn't find package "cacache" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/usr/local/lib/node_modules/yarn/lib/cli.js:750:123)
    at NpmResolver.<anonymous> (/usr/local/lib/node_modules/yarn/lib/cli.js:50683:15)
    at Generator.next (<anonymous>)
    at step (/usr/local/lib/node_modules/yarn/lib/cli.js:310:30)
    at /usr/local/lib/node_modules/yarn/lib/cli.js:321:13
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Couldn't find package "copy-webpack-plugin" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/usr/local/lib/node_modules/yarn/lib/cli.js:750:123)
    at NpmResolver.<anonymous> (/usr/local/lib/node_modules/yarn/lib/cli.js:50683:15)
    at Generator.next (<anonymous>)
    at step (/usr/local/lib/node_modules/yarn/lib/cli.js:310:30)
    at /usr/local/lib/node_modules/yarn/lib/cli.js:321:13
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Couldn't find package "critters" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/usr/local/lib/node_modules/yarn/lib/cli.js:750:123)
    at NpmResolver.<anonymous> (/usr/local/lib/node_modules/yarn/lib/cli.js:50683:15)
    at Generator.next (<anonymous>)
    at step (/usr/local/lib/node_modules/yarn/lib/cli.js:310:30)
    at /usr/local/lib/node_modules/yarn/lib/cli.js:321:13
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Couldn't find package "css-loader" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/usr/local/lib/node_modules/yarn/lib/cli.js:750:123)
    at NpmResolver.<anonymous> (/usr/local/lib/node_modules/yarn/lib/cli.js:50683:15)
    at Generator.next (<anonymous>)
    at step (/usr/local/lib/node_modules/yarn/lib/cli.js:310:30)
    at /usr/local/lib/node_modules/yarn/lib/cli.js:321:13
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Couldn't find package "esbuild-wasm" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/usr/local/lib/node_modules/yarn/lib/cli.js:750:123)
    at NpmResolver.<anonymous> (/usr/local/lib/node_modules/yarn/lib/cli.js:50683:15)
    at Generator.next (<anonymous>)
    at step (/usr/local/lib/node_modules/yarn/lib/cli.js:310:30)
    at /usr/local/lib/node_modules/yarn/lib/cli.js:321:13
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Couldn't find package "glob" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/usr/local/lib/node_modules/yarn/lib/cli.js:750:123)
    at NpmResolver.<anonymous> (/usr/local/lib/node_modules/yarn/lib/cli.js:50683:15)
    at Generator.next (<anonymous>)
    at step (/usr/local/lib/node_modules/yarn/lib/cli.js:310:30)
    at /usr/local/lib/node_modules/yarn/lib/cli.js:321:13
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Couldn't find package "https-proxy-agent" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/usr/local/lib/node_modules/yarn/lib/cli.js:750:123)
    at NpmResolver.<anonymous> (/usr/local/lib/node_modules/yarn/lib/cli.js:50683:15)
    at Generator.next (<anonymous>)
    at step (/usr/local/lib/node_modules/yarn/lib/cli.js:310:30)
    at /usr/local/lib/node_modules/yarn/lib/cli.js:321:13
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Couldn't find package "inquirer" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/usr/local/lib/node_modules/yarn/lib/cli.js:750:123)
    at NpmResolver.<anonymous> (/usr/local/lib/node_modules/yarn/lib/cli.js:50683:15)
    at Generator.next (<anonymous>)
    at step (/usr/local/lib/node_modules/yarn/lib/cli.js:310:30)
    at /usr/local/lib/node_modules/yarn/lib/cli.js:321:13
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Couldn't find package "jsonc-parser" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/usr/local/lib/node_modules/yarn/lib/cli.js:750:123)
    at NpmResolver.<anonymous> (/usr/local/lib/node_modules/yarn/lib/cli.js:50683:15)
```

**Comment by abdallahkadour** [comment]
I appreciate any help.
